### ISSUE TITLE
Node appearing twice in peers list

### ISSUE THREAD

**Issue by Slut** [Joohansson/nanoticker#5]
I run a node monitor which is appearing in the peers list as well as appearing under the IP. It appears that the data is not being aggregated and must be because mynano.ninja doesn't recognize my node yet. Therefore it is showing CPS, BPS and missing node monitor data on one of the entries and node monitor data with missing CPS, BPS telemetry on the other.

I notice you iterate through the peers and look for node monitors so possibly here you could map them?

**Comment by Joohansson** [comment]
What is your node called? The only way to match is by the rep account and if your node is not voting it simply can't match it. I don't know how to solve that? What other data would be available from both the monitor and telemetry? The account comes from the confirmation_quorum RPC command which in turn matches the IP from the telemetry. If the node monitor would report the IP it would have been easier.

**Comment by Slut** [comment]
Could you map the peer IP with the monitor paths which would be one way of matching without needing the rep account?

Specifically [here](https://github.com/Joohansson/nanoticker/blob/master/script/calc-reps.py#L1473-L1528), you could create KVP with the peer IP being the key and an array of node paths as the value, and when you go to verify the monitors you just remove all the ones that don't work and now you've got a matched up peer/monitor

**Comment by Joohansson** [comment]
Yeah that could work, thanks
